---
language: python
python: "2.7"

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: linux
      sudo: required
      dist: xenial

# Install pip
addons:
  apt:
    packages:
    - python-pip

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install ansible
  - pip2 install ansible

  # Check ansible version
  - ansible --version

  # Setup Env
  - mkdir -vp roles/ansible-teamcity-server
  - ansible-galaxy install --roles-path roles ansiblebit.oracle-java
  - mv -v README.md defaults handlers meta tasks templates vars roles/ansible-teamcity-server
  - mv ansible.cfg tests

script:
  - cd tests
  - ansible-playbook ./test.yml -i inventory --syntax-check
  - ansible-playbook -i inventory ./test.yml

after_script:
  - cat /opt/TeamCity/logs/teamcity-server.log

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
