---
language: python
python: "3.5"

sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Setup Env
  - mkdir -vp roles/ansible-teamcity-server
  - ansible-galaxy install --roles-path roles ansiblebit.oracle-java
  - ansible-galaxy install --roles-path roles geerlingguy.mysql
  - mv -v README.md defaults handlers meta tasks templates vars roles/ansible-teamcity-server
  - mv ansible.cfg tests
  - ls -lth -R .

script:
  - cd tests
  - ansible-playbook ./test.yml -i inventory --syntax-check
  - ansible-playbook -i inventory ./test.yml -vvvv

#notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
