---
- name: "Create teamcity group"
  group:
    name: "{{ teamcity_server_group }}"
    state: present
    system: yes

- name: "Create teamcity user"
  user:
    name: "{{ teamcity_server_user }}"
    group: "{{ teamcity_server_group }}"
    groups: "{{ teamcity_server_groups }}"
    state: present
    shell: /bin/bash
    createhome: yes
    system: yes
    home: "{{ teamcity_server_home }}"
