---
- name: "Create mysql-connector dir"
  file:
    path: "{{ teamcity_server_mysql_connector_dir }}"
    state: directory
    owner: "{{ teamcity_server_user }}"
    group: "{{ teamcity_server_group }}"
    mode: 0755

- name: "Create jdbc dir"
  file:
    path: "{{ teamcity_server_jdbc_dir }}"
    state: directory
    owner: "{{ teamcity_server_user }}"
    group: "{{ teamcity_server_group }}"
    mode: 0755

- name: "Download and unpack mysql-connector"
  unarchive:
    src: "http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ teamcity_server_mysql_connector_version }}.tar.gz"
    dest: "{{ teamcity_server_mysql_connector_dir }}"
    copy: no

- name: "Create symlink for mysql-connector"
  file:
    src: "{{ teamcity_server_mysql_connector_dir }}/mysql-connector-java-{{ teamcity_server_mysql_connector_version }}/mysql-connector-java-{{ teamcity_server_mysql_connector_version }}-bin.jar"
    dest: "{{ teamcity_server_jdbc_dir }}/mysql-connector-java-bin.jar"
    state: link
    owner: "{{ teamcity_server_user }}"
    group: "{{ teamcity_server_group }}"

